services:
  - type: web
    name: localpress-api
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DatabaseProvider
        value: Sqlite
